apiVersion: v1
kind: Service
metadata:
  name: {{ include "techtrends.fullname" . }}
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: techtrends
  type: {{ .Values.service.type }}
