# helm/techtrends/templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ include "techtrends.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ include "techtrends.fullname" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: "{{ .Values.service.protocol }}"  # Corrected: protocol should be enclosed in double quotes
  selector:
    app: {{ include "techtrends.fullname" . }}
