apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
  name: shahzaib2468/techtrend
  namespace: {{ .Values.namespace.name }} 
spec:
  ports:
  - port: {{ .Values.service.port }} 
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: nginx
    tag: alpine
  type: {{ .Values.service.type }} 
