# helm/techtrends/values-prod.yaml

namespace:
  name: prod

service:
  port: 7111

image:
  pullPolicy: Always

replicaCount: 1

resources:
  requests:
    memory: 128Mi
    cpu: 350m
  limits:
    memory: 256Mi
    cpu: 500m
