namespace:
  name: prod

service:
  port: 7111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: shahzaib2468/techtrend
  tag: latest
  pullPolicy: Always

replicaCount: 5

resources:
  requests:
    memory: "128Mi"
    cpu: "350m"
  limits:
    memory: "256Mi"
    cpu: "500m"
