name: Publish Docker Image to Docker Hub

on:
  push:
    tags:
      - 'latest'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx (optional, for multi-platform builds)
        uses: docker/setup-buildx-action@v1

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: shahzaib2468/techtrend

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          builder: ${{ secrets.DOCKER_BUILDER_NAME }}  # Specify builder name if using Buildx

      - name: Clean up Docker Buildx (optional)
        uses: docker/setup-buildx-action@v1
        with:
          version: 'latest'
          clean: true



# name: Publish Docker Image to Docker Hub

# on:
#   push:

# jobs:
#   push_to_registry:
#     name: Push Docker image to Docker Hub
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out the repo
#         uses: actions/checkout@v3

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Set up Docker Buildx (optional, for multi-platform builds)
#         uses: docker/setup-buildx-action@v1

#       - name: Extract metadata (tags, labels) for Docker
#         id: meta
#         uses: docker/metadata-action@v4
#         with:
#           images: shahzaib2468/techtrend

#       - name: Build and push Docker image
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           push: true
#           tags: ${{ steps.meta.outputs.tags }}
#           labels: ${{ steps.meta.outputs.labels }}
#           builder: ${{ secrets.DOCKER_BUILDER_NAME }}  # Specify builder name if using Buildx

#       - name: Clean up Docker Buildx (optional)
#         uses: docker/setup-buildx-action@v1
#         with:
#           version: 'latest'
#           clean: true



# name: Publish Docker Image to Docker Hub

# on:
#   push:
#       tags:
#         - 'v*'
      
# jobs:
#   push_to_registry:
#     name: Push Docker image to Docker Hub 
#     runs-on: ubuntu-latest

#     steps:
#       - name: Check out the repo
#         uses: actions/checkout@v3

#       - name: Log in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}

#       - name: Extract metadata (tags, labels) for Docker
#         id: meta
#         uses: docker/metadata-action@v4
#         with:
#           images: shahzaib2468/techtrend
          
#       - name: Build and push Docker image
#         uses: docker/build-push-action@v4
#         with:
#           context: .
#           push: true
#           tags: ${{ steps.meta.outputs.tags }}
#           labels: ${{ steps.meta.outputs.labels }}
